- name: configure the database for Zabbix server
  lineinfile: #to replace a line
    dest: /etc/nginx/conf.d/zabbix.conf
    regexp: "#        listen          8080;"
    line: "         listen          80;"


- name: restarted ans enable mult services 
  service: 
    name: "{{ item }}" 
    state: restarted 
    enabled: yes 
  with_items: 
    - zabbix-server 
    - zabbix-agent 
    - nginx
    - php-fpm
    