- name: Install Zabbix 6 Repository RPM using dnf
  command: dnf install -y https://repo.zabbix.com/zabbix/6.0/rhel/9/x86_64/zabbix-release-6.0-4.el9.noarch.rpm
   
- name: install Zabbix server, frontend, agent
  dnf:
    name:
      - zabbix-server-pgsql
      - zabbix-web-pgsql
      - zabbix-nginx-conf
      - zabbix-sql-scripts
      - zabbix-selinux-policy
      - zabbix-agent 
    state: present

- name: Extract and import Zabbix database schema
  shell: zcat /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz | sudo -u zabbix psql zabbix

- name: configure the database for Zabbix server
  lineinfile: #to replace a line
    dest: /etc/zabbix/zabbix_server.conf
    regexp: "# DBPassword="
    line: "DBPassword={{db_password}}"




